// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package queries

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Circuit struct {
	ID          uuid.UUID
	Name        string
	CircuitName string
	StartDate   time.Time
	EndDate     time.Time
	Status      int32
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type User struct {
	ID        uuid.UUID
	Email     string
	Password  string
	FirstName string
	LastName  string
	Phone     string
	IsActive  sql.NullBool
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}
